#!/usr/bin/env bash
#this script copies the specified file to the server
if !(( $# < 3 ))
then
	scp -i $4 $1 $3@$2:~/;
	ssh -i $4 $3@$2 "ls ~/"
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
