#!/usr/bin/env bash
#this script installs engineX
sudo apt update -y -qq
echo "Installing and configuring nginx..."
sudo apt-get install nginx -y

echo "Setting up the server..."

# starting the server
sudo service nginx start
# backing up the index file


sudo ufw allow 'Nginx HTTP'

sudo chown "$USER":"$USER" /var/www/html
sudo chmod 755 /var/www
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
sudo echo "Hello World!" | sudo dd status=none of=/var/www/html/index.nginx-debian.html
sudo service nginx restart
