#!/bin/env bash
# this script configures the load balancer
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.7
sudo apt-get install haproxy -y
# echo "ENABLED=1" >> /etc/default/haproxy
# sudo mv /etc/haproxy/haproxy.cfg{,.original}
# sudo touch /etc/haproxy/haproxy.cfg 

sudo printf %s "\nfrontend apps_server
	bind *:80
	mode http
	default_backend apps
backend apps
	mode http
	balance roundrobin
	server 144185-web-01 34.229.189.127:80  check
	server 144185-web-02 54.234.70.193:80   check" | sudo tee -a /etc/haproxy/haproxy.cfg


# install load balancer

# colors
blue='\e[1;34m'
brown='\e[0;33m'
green='\e[1;32m'
reset='\033[0m'

echo -e "${blue}Updating and doing some minor checks...${reset}\n"

function install() {
	command -v "$1" &> /dev/null

	#shellcheck disable=SC2181
	if [ $? -ne 0 ]; then
		echo -e "	Installing: ${brown}$1${reset}\n"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq
		echo -e "\n"
	else
		echo -e "	${green}${1} is already installed.${reset}\n"
	fi
}

install haproxy #install haproxy

echo -e "\n${blue}Setting up some minor stuff.${reset}\n"

# backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup


# shellcheck disable=SC2154
# echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi